### ISSUE TITLE
How to Calculate Feature Importance

### ISSUE THREAD

**Issue by MehakManiktala** [manifoldai/merf#33]
Hi,

Thank you for providing this package. I am a PhD student at NC State University. My labmate used your package to conduct her research. Does your code have any provisions to assess the importance of the fixed effect features?

Thanks,
Mehak

**Comment by resdntalien** [comment]
There is an embedded random forest that you can run any feature importance you want on it -- e.g, LIME, SHAP, etc. In a future release of this package we plan on making the fixed effects model something you pass in, so it's more easily accessible.
