### ISSUE TITLE
Unable to install on Python 3.7 using conda

### ISSUE THREAD

**Issue by mariadelmarq** [manifoldai/merf#35]
I'm trying to install merf using conda as described here: https://anaconda.org/leylabmpi/merf, and getting the following error:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - merf -> python[version='>=3.6,<3.7.0a0']

Your python: python=3.7
```

Any advice?

**Comment by resdntalien** [comment]
Hey @mariadelmarq going through a backlog of these issues. I don't maintain the Conda build. You may want to just install from PyPi -- https://pypi.org/project/merf/.
