### ISSUE TITLE
Clearly document the dimensions of Z

### ISSUE THREAD

**Issue by resdntalien** [manifoldai/merf#4]
Has to be array of arrays... so we can transpose and all the matrix math works out.

**Comment by jonathanng** [comment]
Also, it's not clear what Z is or how to use it. Can we just use X here?

**Comment by huanfachen** [comment]
> Also, it's not clear what Z is or how to use it. Can we just use X here?

I have the same question. In the code of `MERFDataGenerator.generate_split_samples()`, Z is a all-one vector. This is also true in the example of Rosemann prediction. 

Is there some explanation on what Z is and how Z is set?
