### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'n_estimators'

### ISSUE THREAD

**Issue by jessie831024** [manifoldai/merf#61]
When trying to set arguments like n_estimators for [MERF](https://manifoldai.github.io/merf/), MERF.fit returns the above initialisation error. It works fine with default setting. 
This seems to suggest that MERF to sklearn random forest API is broken. Is this a version issue? 
I'm using: 
Python 3.9.5
scikit-learn==0.24.2

**Comment by jessie831024** [comment]
I tried using 
Python 3.6.13 
scikit-learn==0.22.2.post1
The error is still there using your notebook examples: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-dd6516a35cc1> in <module>
----> 1 mrf = MERF(n_estimators=300, max_iterations=100)
      2 mrf.fit(X_train, Z_train, clusters_train, y_train)

TypeError: __init__() got an unexpected keyword argument 'n_estimators'`
```

**Comment by fabianegli** [comment]
You have to supply the regressor, not just its parameters. 

```
MERF(fixed_effects_model=RandomForestRegressor(n_estimators=300, max_iterations=100, n_jobs=-1))
```

**Comment by jessie831024** [comment]
Just figured that out. The notebook examples are a little misleading. Thanks.
